# Generated by Django 4.2.5 on 2023-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(help_text='Player ID', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
